# Generated by Django 6.0.6 on 2026-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPasswordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('rpassword', models.CharField(max_length=500)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
