# Generated by Django 6.0.6 on 2026-06-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
