# Generated by Django 6.0.6 on 2026-06-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_journal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='show_on_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='show_timestamp',
            field=models.BooleanField(default=True),
        ),
    ]
