# Generated by Django 6.0.6 on 2026-06-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_journal_show_on_home_journal_show_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='is_seo',
            field=models.BooleanField(default=False),
        ),
    ]
