# Generated by Django 6.0.6 on 2026-06-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_journal_is_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=200)),
                ('os', models.CharField(blank=True, max_length=200)),
                ('device', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('is_bot', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
