# Generated by Django 6.0.6 on 2026-07-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
