# Generated by Django 6.0.6 on 2026-07-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_visitorlog_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latest_trial_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
