# Generated by Django 6.0.6 on 2026-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_latest_trial_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='latest_trial_level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
