# Generated by Django 6.0.6 on 2026-07-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_latest_trial_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_library_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_self_registered',
            field=models.BooleanField(default=False),
        ),
    ]
