# Generated by Django 6.0.6 on 2026-07-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabtest',
            name='passage',
            field=models.TextField(blank=True),
        ),
    ]
