# Generated by Django 6.0.6 on 2026-06-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo')], max_length=10),
        ),
    ]
