# Generated by Django 6.0.6 on 2026-06-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_material_embed_url_alter_material_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video (Sunucuda)'), ('youtube', 'YouTube Gömme'), ('vimeo', 'Vimeo Gömme')], max_length=10),
        ),
    ]
