# Generated by Django 6.0.6 on 2026-06-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_journal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
