# Generated by Django 6.0.6 on 2026-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_carouselitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video (Sunucuda)'), ('youtube', 'YouTube Gömme'), ('vimeo', 'Vimeo Gömme'), ('image', 'Görsel (PNG/JPEG)')], max_length=10),
        ),
    ]
