# Generated by Django 6.0.6 on 2026-07-09 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_material_material_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='visible_active_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active_course',
            field=models.BooleanField(default=False),
        ),
    ]
